version: "2"
services:
  web:
    build: ./
    links:
      - data
    ports:
      - "5000:5000"
    volumes:
      - .:/home/TODO_BE
  data:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: todolists
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro
