"""empty message

Revision ID: 63508e2bd461
Revises: 
Create Date: 2018-07-30 03:11:10.528807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63508e2bd461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('todolist_id', sa.Integer(), nullable=False),
    sa.Column('useremail', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('todolist_id')
    )
    op.create_table('modified_date',
    sa.Column('modified_date_id', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('todolist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['todolist_id'], ['todo_list.todolist_id'], ),
    sa.PrimaryKeyConstraint('modified_date_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modified_date')
    op.drop_table('todo_list')
    # ### end Alembic commands ###
