"""empty message

Revision ID: b44cf1edaed8
Revises: 5425c022f18d
Create Date: 2018-07-26 21:01:22.924222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44cf1edaed8'
down_revision = '5425c022f18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_list', sa.Column('useremail', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_list', 'useremail')
    # ### end Alembic commands ###
